# declare the global variables

from pathlib import Path

CURRENT_DIR_STR = str
DATA_URL_STR = str
BACKUP_DATA_URL_STR = str
UPDATE_DATETIME_STR = str
DATA_FILE_STR = str
OLD_FILE_STR = str
UPDATE_FILE_STR = str
COUNTRY_FILE_STR = str
COVID_PACKAGE_STR = str
DATA_FILE_PATH = Path
OLD_FILE_PATH = Path
UPDATE_FILE_PATH = Path
COUNTRY_FILE_PATH = Path
COVID_PACKAGE_PATH = Path
